/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Administrator
 */
public class KirimanPaket extends javax.swing.JFrame {
        String Tanggal, Penerima, JK, Tipe, Jenis, Kurir="";
        int PilihTipe, PilihJenis;
    public KirimanPaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel21552011440 = new javax.swing.JPanel();
        LabelJudul21552011440 = new javax.swing.JLabel();
        LabelPenerima21552011440 = new javax.swing.JLabel();
        LabelTanggal21552011440 = new javax.swing.JLabel();
        TextFieldPenerima21552011440 = new javax.swing.JTextField();
        LabelJK21552011440 = new javax.swing.JLabel();
        JKL21552011440 = new javax.swing.JRadioButton();
        JKLP21552011440 = new javax.swing.JRadioButton();
        LabelTipePaket21552011440 = new javax.swing.JLabel();
        ComboBoxTP21552011440 = new javax.swing.JComboBox<>();
        LabelJenisPaket21552011440 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListJenisPaket21552011440 = new javax.swing.JList<>();
        LabelKurir21552011440 = new javax.swing.JLabel();
        CheckJNE21552011440 = new javax.swing.JCheckBox();
        CheckSiCepat21552011440 = new javax.swing.JCheckBox();
        CheckGG21552011440 = new javax.swing.JCheckBox();
        CheckJnT21552011440 = new javax.swing.JCheckBox();
        ButtonProses21552011440 = new javax.swing.JButton();
        ButtonBersihkan21552011440 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TampilkanTextArea21552011440 = new javax.swing.JTextArea();
        DateChooser21552011440 = new datechooser.beans.DateChooserCombo();
        ToolBarKeluar21552011440 = new javax.swing.JToolBar();
        ButtonRefresh21552011440 = new javax.swing.JButton();
        ToolBarRefresh21552011440 = new javax.swing.JToolBar();
        ButtonKeluar21552011440 = new javax.swing.JButton();
        MenuBar21552011440 = new javax.swing.JMenuBar();
        Menu21552011440 = new javax.swing.JMenu();
        MenuItemProsess21552011440 = new javax.swing.JMenuItem();
        MenuItemBersihkan21552011440 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Panel21552011440.setBackground(new java.awt.Color(0, 204, 204));

        LabelJudul21552011440.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LabelJudul21552011440.setForeground(new java.awt.Color(255, 0, 0));
        LabelJudul21552011440.setText("LAPORAN KIRIMAN PAKET ");

        LabelPenerima21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelPenerima21552011440.setText("ADMIN PENERIMA");

        LabelTanggal21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelTanggal21552011440.setText("TANGGAL BARANG MASUK");

        LabelJK21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelJK21552011440.setText("JENIS KELAMIN");

        JKL21552011440.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(JKL21552011440);
        JKL21552011440.setText("LAKI-LAKI");

        JKLP21552011440.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(JKLP21552011440);
        JKLP21552011440.setText("PEREMPUAN");

        LabelTipePaket21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelTipePaket21552011440.setText("TIPE PAKET ");

        ComboBoxTP21552011440.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Telah Dibayar", "Cash On Delivery(COD)" }));

        LabelJenisPaket21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelJenisPaket21552011440.setText("JENIS PAKET ");

        ListJenisPaket21552011440.setBackground(new java.awt.Color(0, 204, 204));
        ListJenisPaket21552011440.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "REGULAR", "CEPAT", "SUPER", "SAMEDAY", "INSTANT" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListJenisPaket21552011440);

        LabelKurir21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        LabelKurir21552011440.setText("KURIR");

        CheckJNE21552011440.setBackground(new java.awt.Color(0, 204, 204));
        CheckJNE21552011440.setText("JNE");
        CheckJNE21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckJNE21552011440MouseClicked(evt);
            }
        });

        CheckSiCepat21552011440.setBackground(new java.awt.Color(0, 204, 204));
        CheckSiCepat21552011440.setText("SiCepat");
        CheckSiCepat21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckSiCepat21552011440MouseClicked(evt);
            }
        });

        CheckGG21552011440.setBackground(new java.awt.Color(0, 204, 204));
        CheckGG21552011440.setText("GRAB/GOJEK");
        CheckGG21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckGG21552011440MouseClicked(evt);
            }
        });

        CheckJnT21552011440.setBackground(new java.awt.Color(0, 204, 204));
        CheckJnT21552011440.setText("J&T");
        CheckJnT21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckJnT21552011440MouseClicked(evt);
            }
        });

        ButtonProses21552011440.setBackground(new java.awt.Color(0, 0, 0));
        ButtonProses21552011440.setForeground(new java.awt.Color(255, 255, 255));
        ButtonProses21552011440.setText("PROSES");
        ButtonProses21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProses21552011440ActionPerformed(evt);
            }
        });

        ButtonBersihkan21552011440.setBackground(new java.awt.Color(0, 0, 0));
        ButtonBersihkan21552011440.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBersihkan21552011440.setText("BERSIHKAN");
        ButtonBersihkan21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBersihkan21552011440ActionPerformed(evt);
            }
        });

        TampilkanTextArea21552011440.setEditable(false);
        TampilkanTextArea21552011440.setBackground(new java.awt.Color(0, 204, 204));
        TampilkanTextArea21552011440.setColumns(20);
        TampilkanTextArea21552011440.setRows(5);
        jScrollPane2.setViewportView(TampilkanTextArea21552011440);

        DateChooser21552011440.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    ToolBarKeluar21552011440.setBackground(new java.awt.Color(0, 204, 255));
    ToolBarKeluar21552011440.setRollover(true);

    ButtonRefresh21552011440.setBackground(new java.awt.Color(204, 204, 204));
    ButtonRefresh21552011440.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_folder_cross_delete_error_file_icon_219431.png"))); // NOI18N
    ButtonRefresh21552011440.setText("sadadas");
    ButtonRefresh21552011440.setToolTipText("Keluar Aplikasi");
    ButtonRefresh21552011440.setFocusable(false);
    ButtonRefresh21552011440.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    ButtonRefresh21552011440.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    ButtonRefresh21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonRefresh21552011440ActionPerformed(evt);
        }
    });
    ToolBarKeluar21552011440.add(ButtonRefresh21552011440);

    ToolBarRefresh21552011440.setBackground(new java.awt.Color(0, 204, 255));
    ToolBarRefresh21552011440.setRollover(true);

    ButtonKeluar21552011440.setBackground(new java.awt.Color(204, 204, 204));
    ButtonKeluar21552011440.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_document_list_paper_file_icon_219450.png"))); // NOI18N
    ButtonKeluar21552011440.setToolTipText("Refresh Aplikasi");
    ButtonKeluar21552011440.setFocusable(false);
    ButtonKeluar21552011440.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    ButtonKeluar21552011440.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    ButtonKeluar21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonKeluar21552011440ActionPerformed(evt);
        }
    });
    ToolBarRefresh21552011440.add(ButtonKeluar21552011440);

    javax.swing.GroupLayout Panel21552011440Layout = new javax.swing.GroupLayout(Panel21552011440);
    Panel21552011440.setLayout(Panel21552011440Layout);
    Panel21552011440Layout.setHorizontalGroup(
        Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Panel21552011440Layout.createSequentialGroup()
            .addComponent(ToolBarRefresh21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel21552011440Layout.createSequentialGroup()
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel21552011440Layout.createSequentialGroup()
                            .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(Panel21552011440Layout.createSequentialGroup()
                                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelTanggal21552011440)
                                        .addComponent(LabelPenerima21552011440)
                                        .addComponent(LabelJK21552011440)
                                        .addComponent(LabelTipePaket21552011440)
                                        .addComponent(LabelJenisPaket21552011440)
                                        .addComponent(LabelKurir21552011440))
                                    .addGap(32, 32, 32)
                                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(Panel21552011440Layout.createSequentialGroup()
                                                .addComponent(JKL21552011440)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JKLP21552011440))
                                            .addComponent(TextFieldPenerima21552011440)
                                            .addComponent(ComboBoxTP21552011440, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1))
                                        .addGroup(Panel21552011440Layout.createSequentialGroup()
                                            .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CheckGG21552011440)
                                                .addComponent(CheckJNE21552011440))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CheckSiCepat21552011440)
                                                .addComponent(CheckJnT21552011440)))
                                        .addGroup(Panel21552011440Layout.createSequentialGroup()
                                            .addComponent(ButtonProses21552011440)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ButtonBersihkan21552011440))
                                        .addComponent(DateChooser21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(Panel21552011440Layout.createSequentialGroup()
                                    .addComponent(LabelJudul21552011440)
                                    .addGap(14, 14, 14)))
                            .addGap(95, 95, 95)))
                    .addContainerGap())
                .addGroup(Panel21552011440Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ToolBarKeluar21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    Panel21552011440Layout.setVerticalGroup(
        Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Panel21552011440Layout.createSequentialGroup()
            .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel21552011440Layout.createSequentialGroup()
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ToolBarRefresh21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelJudul21552011440, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelTanggal21552011440)
                        .addComponent(DateChooser21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelPenerima21552011440)
                        .addComponent(TextFieldPenerima21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelJK21552011440)
                        .addComponent(JKL21552011440)
                        .addComponent(JKLP21552011440))
                    .addGap(18, 18, 18)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelTipePaket21552011440)
                        .addComponent(ComboBoxTP21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelJenisPaket21552011440)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckJNE21552011440)
                        .addComponent(LabelKurir21552011440)
                        .addComponent(CheckSiCepat21552011440))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckGG21552011440)
                        .addComponent(CheckJnT21552011440))
                    .addGap(18, 18, 18)
                    .addGroup(Panel21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonProses21552011440)
                        .addComponent(ButtonBersihkan21552011440)))
                .addComponent(ToolBarKeluar21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    Menu21552011440.setMnemonic('f');
    Menu21552011440.setText("Tools");
    Menu21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Menu21552011440ActionPerformed(evt);
        }
    });

    MenuItemProsess21552011440.setMnemonic('p');
    MenuItemProsess21552011440.setText("Prosess");
    MenuItemProsess21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MenuItemProsess21552011440ActionPerformed(evt);
        }
    });
    Menu21552011440.add(MenuItemProsess21552011440);

    MenuItemBersihkan21552011440.setMnemonic('b');
    MenuItemBersihkan21552011440.setText("Bersihkan");
    MenuItemBersihkan21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MenuItemBersihkan21552011440ActionPerformed(evt);
        }
    });
    Menu21552011440.add(MenuItemBersihkan21552011440);

    MenuBar21552011440.add(Menu21552011440);

    setJMenuBar(MenuBar21552011440);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Panel21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Panel21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonProses21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProses21552011440ActionPerformed
        Tanggal=DateChooser21552011440.getText();
        Penerima = TextFieldPenerima21552011440.getText();
        
        PilihTipe=ComboBoxTP21552011440.getSelectedIndex();
        switch(PilihTipe)
        {
            case 0:
                Tipe = "-";
                break;
            case 1:
                Tipe = "TELAH DIBAYAR"; 
                break;
            case 2:
                Tipe= "CASH ON DELIVERY (COD)";
                break;
        }
        PilihJenis=ListJenisPaket21552011440.getSelectedIndex();
        switch(PilihJenis)
        {
            case 0:
                Jenis = "REGULAR";
                break;
            case 1:
                Jenis = "CEPAT";
                break;
            case 2:
                Jenis = "SUPER";
                break;
            case 3:
                Jenis = "SAMEDAY";
                break;
            case 4:
                Jenis = "INSTANT";
                break; 
        }
        if(JKL21552011440.isSelected()){
            JK="LAKI-LAKI";
        }else if(JKLP21552011440.isSelected()){
            JK="PEREMPUAN";
        } else
            JK="-";
                
        TampilkanTextArea21552011440.setText("TANGGAL BARANG MASUK\t    :"+Tanggal+"\nADMIN PENERIMA\t    :"+Penerima+"\nJENIS KELAMIN\t    :"+JK+"\nTIPE PAKET\t\t    :"+Tipe+"\nJENIS PAKET\t\t    :"+Jenis+"\nKURIR\t\t    :"+Kurir);
    }//GEN-LAST:event_ButtonProses21552011440ActionPerformed

    private void ButtonBersihkan21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersihkan21552011440ActionPerformed
        TextFieldPenerima21552011440.setText("");
        TampilkanTextArea21552011440.setText("");
        CheckGG21552011440.setSelected(false);
        CheckJNE21552011440.setSelected(false);
        CheckJnT21552011440.setSelected(false);
        CheckSiCepat21552011440.setSelected(false);
    }//GEN-LAST:event_ButtonBersihkan21552011440ActionPerformed

    private void CheckJNE21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckJNE21552011440MouseClicked
         if(CheckJNE21552011440.isSelected()){
            Kurir= Kurir + CheckJNE21552011440.getText()+", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckJNE21552011440MouseClicked

    private void CheckSiCepat21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckSiCepat21552011440MouseClicked
         if(CheckSiCepat21552011440.isSelected()){
            Kurir= Kurir + CheckSiCepat21552011440.getText()+", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckSiCepat21552011440MouseClicked

    private void CheckGG21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckGG21552011440MouseClicked
         if(CheckGG21552011440.isSelected()){
            Kurir= Kurir + CheckGG21552011440.getText() +", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckGG21552011440MouseClicked

    private void CheckJnT21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckJnT21552011440MouseClicked
         if(CheckJnT21552011440.isSelected()){
            Kurir= Kurir + CheckJnT21552011440.getText() + ", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckJnT21552011440MouseClicked

    private void ButtonRefresh21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefresh21552011440ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonRefresh21552011440ActionPerformed

    private void Menu21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu21552011440ActionPerformed

    }//GEN-LAST:event_Menu21552011440ActionPerformed

    private void MenuItemBersihkan21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBersihkan21552011440ActionPerformed
        TextFieldPenerima21552011440.setText("");
        TampilkanTextArea21552011440.setText("");
        CheckGG21552011440.setSelected(false);
        CheckJNE21552011440.setSelected(false);
        CheckJnT21552011440.setSelected(false);
        CheckSiCepat21552011440.setSelected(false);
    }//GEN-LAST:event_MenuItemBersihkan21552011440ActionPerformed

    private void MenuItemProsess21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProsess21552011440ActionPerformed
         Tanggal=DateChooser21552011440.getText();
        Penerima = TextFieldPenerima21552011440.getText();
        
        PilihTipe=ComboBoxTP21552011440.getSelectedIndex();
        switch(PilihTipe)
        {
            case 0:
                Tipe = "-";
                break;
            case 1:
                Tipe = "TELAH DIBAYAR"; 
                break;
            case 2:
                Tipe= "CASH ON DELIVERY (COD)";
                break;
        }
        PilihJenis=ListJenisPaket21552011440.getSelectedIndex();
        switch(PilihJenis)
        {
            case 0:
                Jenis = "REGULAR";
                break;
            case 1:
                Jenis = "CEPAT";
                break;
            case 2:
                Jenis = "SUPER";
                break;
            case 3:
                Jenis = "SAMEDAY";
                break;
            case 4:
                Jenis = "INSTANT";
                break; 
        }
        if(JKL21552011440.isSelected()){
            JK="LAKI-LAKI";
        }else if(JKLP21552011440.isSelected()){
            JK="PEREMPUAN";
        } else
            JK="-";
                
        TampilkanTextArea21552011440.setText("TANGGAL BARANG MASUK\t    :"+Tanggal+"\nADMIN PENERIMA\t    :"+Penerima+"\nJENIS KELAMIN\t    :"+JK+"\nTIPE PAKET\t\t    :"+Tipe+"\nJENIS PAKET\t\t    :"+Jenis+"\nKURIR\t\t    :"+Kurir);
    }//GEN-LAST:event_MenuItemProsess21552011440ActionPerformed

    private void ButtonKeluar21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluar21552011440ActionPerformed
       new KirimanPaket().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ButtonKeluar21552011440ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KirimanPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBersihkan21552011440;
    private javax.swing.JButton ButtonKeluar21552011440;
    private javax.swing.JButton ButtonProses21552011440;
    private javax.swing.JButton ButtonRefresh21552011440;
    private javax.swing.JCheckBox CheckGG21552011440;
    private javax.swing.JCheckBox CheckJNE21552011440;
    private javax.swing.JCheckBox CheckJnT21552011440;
    private javax.swing.JCheckBox CheckSiCepat21552011440;
    private javax.swing.JComboBox<String> ComboBoxTP21552011440;
    private datechooser.beans.DateChooserCombo DateChooser21552011440;
    private javax.swing.JRadioButton JKL21552011440;
    private javax.swing.JRadioButton JKLP21552011440;
    private javax.swing.JLabel LabelJK21552011440;
    private javax.swing.JLabel LabelJenisPaket21552011440;
    private javax.swing.JLabel LabelJudul21552011440;
    private javax.swing.JLabel LabelKurir21552011440;
    private javax.swing.JLabel LabelPenerima21552011440;
    private javax.swing.JLabel LabelTanggal21552011440;
    private javax.swing.JLabel LabelTipePaket21552011440;
    private javax.swing.JList<String> ListJenisPaket21552011440;
    private javax.swing.JMenu Menu21552011440;
    private javax.swing.JMenuBar MenuBar21552011440;
    private javax.swing.JMenuItem MenuItemBersihkan21552011440;
    private javax.swing.JMenuItem MenuItemProsess21552011440;
    private javax.swing.JPanel Panel21552011440;
    private javax.swing.JTextArea TampilkanTextArea21552011440;
    private javax.swing.JTextField TextFieldPenerima21552011440;
    private javax.swing.JToolBar ToolBarKeluar21552011440;
    private javax.swing.JToolBar ToolBarRefresh21552011440;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
